# ==== Étape 1 : Build de l'application avec Maven (image temporaire) ====
FROM maven:3.9.10-eclipse-temurin-17 AS builder

WORKDIR /app
COPY pom.xml .
COPY src ./src

RUN mvn dependency:go-offline
RUN mvn clean package -DskipTests

# ==== Étape 2 : Image finale légère ====
FROM eclipse-temurin:17-jre-alpine

RUN addgroup --system spring && adduser --system --ingroup spring spring
USER spring

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/app.jar"]
